server:
  port: 8888


spring:
  application:
    name: config-service
  profiles:
    active: native # 이 설정을 적용하면 git 설정은 무시됨
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/workspace/spring-msa/native-file-repo
        git:
          uri: https://github.com/jjh5887/spring-cloud-config.git
#          username: [your username]
#          password: [your password]
#          uri: file:///Users/jung-gwonho/workspace/spring-msa/git-local-repo
